parameters:
  azureConnectionName: ''
  resourceGroupName: ''
  deploymentFolder: ''
  deploymentMode: ''

jobs:
- job: "Deploy${{ parameters.resourceGroupName }}"
  pool:
    vmImage: windows-2019
  steps:
  - task: AzureResourceGroupDeployment@2
    displayName: Deploy Resourcegroup ${{ parameters.resourceGroupName }}
    inputs:
      ConnectedServiceName: ${{ parameters.azureConnectionName }}
      action: 'Create Or Update Resource Group'
      resourceGroupName: ${{ parameters.resourceGroupName }}
      location: 'West Europe'
      csmFile: "${{ parameters.deploymentFolder }}/Azuredeploy.json"
      csmParametersFile: "${{ parameters.deploymentFolder }}/Azuredeploy.parameters.json"
      deploymentMode: ${{ parameters.deploymentMode }}